// Code generated by goyacc -o pkg/ast/ast.go pkg/ast/ast.y. DO NOT EDIT.

//line pkg/ast/ast.y:2
package ast

import __yyfmt__ "fmt"

//line pkg/ast/ast.y:2

import (
	"fmt"
	"strings"

	"github.com/elliotcourant/arkdb/pkg/tree"
	"go/constant"
)

// MaxUint is the maximum value of an uint.
const MaxUint = ^uint(0)

// MaxInt is the maximum value of an int.
const MaxInt = int(MaxUint >> 1)

//line pkg/ast/ast.y:31
type yySymType struct {
	yys   int
	id    int32
	pos   int32
	str   string
	union sqlSymUnion
}

const ALTER = 57346
const BEGIN = 57347
const COMMIT = 57348
const CREATE = 57349
const DATABASE = 57350
const IDENT = 57351

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ALTER",
	"BEGIN",
	"COMMIT",
	"CREATE",
	"DATABASE",
	"IDENT",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line pkg/ast/ast.y:63
